import { useLiveQuery } from 'dexie-react-hooks';
import { useState, type FormEvent } from 'react';
import { useAuth } from '../../app/AuthContext';
import { db } from '../../db/database';
import { commitLocalMutation } from '../../db/localMutation';
import type { Student } from '../../domain/types';
import { AvatarRenderer } from '../avatars/AvatarRenderer';

export function StudentsPage() {
  const { active } = useAuth(); const [open, setOpen] = useState(false); const [error, setError] = useState<string | null>(null);
  const students = useLiveQuery(() => db.students.where('schoolId').equals(active!.schoolId).filter((item) => !item.deletedAt).sortBy('displayName'), [active!.schoolId]) ?? [];
  async function createStudent(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const code = String(form.get('code')).trim(); const name = String(form.get('name')).trim(); if (!code || !name) return; const duplicate = await db.students.where({ schoolId: active!.schoolId, studentCode: code }).first(); if (duplicate) { setError('รหัสนักเรียนนี้มีอยู่แล้ว'); return; } const now = new Date().toISOString(); const record: Student = { id: crypto.randomUUID(), schoolId: active!.schoolId, profileId: null, studentCode: code, displayName: name, avatarIndex: crypto.getRandomValues(new Uint16Array(1))[0]! % 144, avatarConfig: null, status: 'active', version: 0, createdAt: now, updatedAt: now, deletedAt: null }; await commitLocalMutation('student', record); event.currentTarget.reset(); setOpen(false); }
  return <><section className="page-heading"><div><span className="eyebrow">ข้อมูลตามสิทธิ์</span><h1>นักเรียน</h1><p>{students.length} คนใน authorized offline projection</p></div>{['admin','teacher'].includes(active!.role) && <button className="primary-button" onClick={() => setOpen(true)}>+ เพิ่มนักเรียน</button>}</section>{open && <form className="inline-form panel" onSubmit={(event) => void createStudent(event)}><div className="panel-heading"><h2>เพิ่มนักเรียน</h2><button type="button" className="icon-button" onClick={() => setOpen(false)}>×</button></div><div className="form-grid"><label>รหัสนักเรียน<input name="code" required /></label><label>ชื่อ-นามสกุล<input name="name" required /></label></div>{error && <div className="alert error">{error}</div>}<button className="primary-button">บันทึกในเครื่อง</button></form>}<section className="panel data-panel">{students.length === 0 ? <div className="empty-state"><span>◉</span><h3>ยังไม่มีนักเรียนในเครื่องนี้</h3><p>เพิ่มนักเรียนหรือนำเข้าจากระบบ Cloud ที่ได้รับอนุญาต</p></div> : <div className="student-grid">{students.map((student) => <article className="student-card" key={student.id}><AvatarRenderer avatarIndex={student.avatarIndex} config={student.avatarConfig} size={84} /><div><strong>{student.displayName}</strong><span>{student.studentCode}</span><small className="status-chip success">ใช้งาน</small></div></article>)}</div>}</section></>;
}
