import { useLiveQuery } from 'dexie-react-hooks';
import { useAuth } from '../../app/AuthContext';
import { db } from '../../db/database';

export function DashboardPage() {
  const { active } = useAuth();
  const counts = useLiveQuery(async () => ({ students: await db.students.where('schoolId').equals(active!.schoolId).filter((s) => !s.deletedAt).count(), pending: await db.syncQueue.where({ schoolId: active!.schoolId, status: 'pending' }).count(), classes: await db.classes.where('schoolId').equals(active!.schoolId).count() }), [active!.schoolId]);
  return <><section className="page-heading"><div><span className="eyebrow">ภาพรวมวันนี้</span><h1>สวัสดี {active!.displayName}</h1><p>ข้อมูลสำคัญของ {active!.schoolName}</p></div><button className="primary-button">+ สร้างรายการ</button></section><section className="metric-grid"><article className="metric-card violet"><span>นักเรียนในเครื่อง</span><strong>{counts?.students ?? '—'}</strong><small>authorized projection</small></article><article className="metric-card teal"><span>ห้องเรียน</span><strong>{counts?.classes ?? '—'}</strong><small>ตามสิทธิ์ของคุณ</small></article><article className="metric-card amber"><span>รอซิงก์</span><strong>{counts?.pending ?? '—'}</strong><small>รายการไม่สูญหายเมื่อปิดแอป</small></article><article className="metric-card blue"><span>สถานะระบบ</span><strong className="metric-word">พร้อมใช้</strong><small>local database online</small></article></section><section className="dashboard-grid"><article className="panel"><div className="panel-heading"><h2>งานด่วน</h2><span className="status-chip success">วันนี้</span></div><div className="empty-state"><span>✓</span><h3>ยังไม่มีงานค้างในเครื่อง</h3><p>รายการที่ต้องดำเนินการจะปรากฏที่นี่</p></div></article><article className="panel"><div className="panel-heading"><h2>ความพร้อมของระบบ</h2></div><ul className="health-list"><li><span className="health-dot ok"/>Local database<strong>พร้อม</strong></li><li><span className="health-dot ok"/>PWA shell<strong>พร้อม</strong></li><li><span className="health-dot ok"/>Security context<strong>{active!.role}</strong></li><li><span className="health-dot ok"/>Sync queue<strong>{counts?.pending ?? 0} pending</strong></li></ul></article></section></>;
}
